### ISSUE TITLE
failing on julia master

### ISSUE THREAD

**Issue by vtjnash** [JuliaCI/Coverage.jl#109]
https://build.julialang.org/builders/coverage_ubuntu14.04-x64/builds/493/steps/Gather%20test%20results%20and%20Submit/logs/stdio
```julia
Result of submission:
Array{UInt8}((69,)) UInt8[0x7b,0x22,0x6d,0x65,0x73,0x73,0x61,0x67,0x65,0x22  …  0x31,0x36,0x33,0x32,0x36,0x36,0x39,0x39,0x22,0x7d]
WARNING: submit_token is deprecated, use submit_local instead.
 in depwarn(::String, ::Symbol) at ./deprecated.jl:64
 in submit_token(::Array{Coverage.FileCoverage,1}, ::Vararg{Any,N}) at ./deprecated.jl:30
 in eval(::Module, ::Any) at ./boot.jl:234
 in process_options(::Base.JLOptions) at ./client.jl:239
 in _start() at ./client.jl:318
while loading no file, in expression starting on line 0
ERROR: MethodError: no method matching submit_local(::Array{Coverage.FileCoverage,1}, ::String, ::String)
Closest candidates are:
  submit_local(::Array{Coverage.FileCoverage,1}; kwargs...)
 in submit_token(::Array{Coverage.FileCoverage,1}, ::Vararg{Any,N}) at ./deprecated.jl:32
 in eval(::Module, ::Any) at ./boot.jl:234
 in process_options(::Base.JLOptions) at ./client.jl:239
 in _start() at ./client.jl:318
program finished with exit code 1
```

**Comment by tkelman** [comment]
This package does not currently have an owner. It will need to be maintained by the community until that changes.

**Comment by tkelman** [comment]
This package does not currently have an owner. It will need to be maintained by the community until that changes.

**Comment by tkelman** [comment]
There's a chance this might actually be happening in one or both of CoverageBase.jl and/or the buildbot code at https://github.com/staticfloat/julia-buildbot, I'm not positive. cc @staticfloat maybe.

**Comment by staticfloat** [comment]
Looks like this is happening because the buildbot script calls [`Codecov.submit_token(results, Base.GIT_VERSION_INFO.commit, Base.GIT_VERSION_INFO.branch)`](https://github.com/staticfloat/julia-buildbot/blob/757d7b7f0f73a72d0802bc44ff1b395361f7083d/master/coverage.py#L59), which gets caught by [this `@deprecate` macro](https://github.com/JuliaCI/Coverage.jl/blob/6e81001ad600c12c821d9fa8623f7b26ff3fa809/src/codecovio.jl#L105), which forward to the [`submit_local()` function](https://github.com/JuliaCI/Coverage.jl/blob/6e81001ad600c12c821d9fa8623f7b26ff3fa809/src/codecovio.jl#L91), whose method signature obviously doesn't match that invocation.
