### ISSUE TITLE
Wrong missing lines

### ISSUE THREAD

**Issue by mistguy** [JuliaCI/Coverage.jl#132]
Using Coverage.jl, my repository has some false missing lines such as `end` and comments.

see https://codecov.io/gh/mistguy/Hop.jl/src/8f204ade24270ee1b32a794a94b2078b35cb9a97/src/Hop.jl

**Comment by mistguy** [comment]
Related: https://discourse.julialang.org/t/is-there-a-problem-with-codecov-and-nightly/5517

**Comment by kmsquire** [comment]
Also seen in DataStructures.jl, e.g.: https://codecov.io/gh/JuliaCollections/DataStructures.jl/compare/7178c6082cc973599bd3ec897eaa8d430c112b98...625bcae0ff54a0af08b57991197ca996bbb5065e/src/src/balanced_tree.jl

**Comment by bramtayl** [comment]
Anyone have any breadcrumbs? Causing me some issues and I'd be happy to take a stab if I knew where to start

**Comment by fjarri** [comment]
For what it's worth, here are my observations:
- Coveralls still displays the coverage correctly, the problem only appears with Codecov
- When my package is tested on Travis, the first platforms to finish are v0.6 Mac and Linux; after they submit their results, Codecov displays the correct (high) coverage. When the first nightly result comes in (usually from Linux, but I don't think it's important) and is incorporated, the displayed coverage suddenly drops 30%. 

The last one is especially strange, since I assumed that coverage results are joined, so if you have X% coverage on one platform, you will have at least X% coverage in total.

**Comment by iamed2** [comment]
> The last one is especially strange, since I assumed that coverage results are joined, so if you have X% coverage on one platform, you will have at least X% coverage in total.

My guess is that the nightly version is adding (uncovered) code lines which weren't marked as code lines in the previous versions.

**Comment by fingolfin** [comment]
I just had a look at https://codecov.io/gh/mistguy/Hop.jl/src/master/src/Hop.jl and could not see any `end` statements that were "red", so I am assuming this issue has been resolved in the meantime. If not, feel free to reopen and provide additional details. Thank you!
