### ISSUE TITLE
Inconsistent badges in the README

### ISSUE THREAD

**Issue by fingolfin** [JuliaCI/Coverage.jl#181]
The README.md has these badges at the top:
```
[![Coverage](http://pkg.julialang.org/badges/Coverage_0.6.svg)](http://pkg.julialang.org/?pkg=Coverage)
[![Coverage](http://pkg.julialang.org/badges/Coverage_0.7.svg)](http://pkg.julialang.org/?pkg=Coverage)
```
rendering as
[![Coverage](http://pkg.julialang.org/badges/Coverage_0.6.svg)](http://pkg.julialang.org/?pkg=Coverage)
[![Coverage](http://pkg.julialang.org/badges/Coverage_0.7.svg)](http://pkg.julialang.org/?pkg=Coverage)

For me, they show the versions 0.6.0 (for Julia 0.6) resp. 0.5.3 (for Julia 0.7).

* why is 0.5.3 shown for Julia 0.7, and not at least 0.6.0, or even better, 0.6.1?
* is there also a badge for Julia 1.0?
* is just tagging `v0.6.1` really enough to "release" a version of this package? `Pkg.add("Coverage")` still gives me 0.6.0.
* does it even make sense to provide links to https://pkg.julialang.org, given that this site was "Last updated 2018-08-05" and still lists only Julia 0.6.3 and 0.7.0-dev  ?
* where is any of this documented?

**Comment by ararslan** [comment]
All good questions, I'll take them one at a time.

1. > Why is 0.5.3 shown for Julia 0.7, and not at least 0.6.0, or even better, 0.6.1?

   For some background, [PackageEvaluator](https://github.com/JuliaCI/PackageEvaluator.jl) runs every other day and it's what updates badges and the pkg.julialang.org site. It is sad and broken and unmaintained. It is being superseded by a new system, which is not yet hooked into the badge and website updating machinery. That is on my to-do list in my spare time.

   PackageEvaluator used to run on Julia 0.6 and Julia 0.7, until the changes in 0.7 became so numerous that PackageEvaluator couldn't keep up. I'm not sure what it's running anymore, to be honest. I don't maintain it anymore, but last I checked it couldn't run any 0.7 jobs. Who knows why. All of the existing 0.7 badges are from the last time PackageEvaluator successfully finished a 0.7 job, which is why they're old. You can basically ignore them for now, as they're effectively meaningless.

   As for why Coverage's badge shows 0.6.0, see question 3 below. It also won't be updated until the next successful PackageEvaluator run after that.

2. > Is there also a badge for Julia 1.0?

   Not yet. That will happen once the new system is hooked up into badge generation.

3. > Is just tagging v0.6.1 really enough to "release" a version of this package? Pkg.add("Coverage") still gives me 0.6.0.

   Yes, mostly. Changes need to be merged into METADATA in order for new versions to be installable.

4. > Does it even make sense to provide links to https://pkg.julialang.org, given that this site was "Last updated 2018-08-05" and still lists only Julia 0.6.3 and 0.7.0-dev ?

   Probably not, but hopefully the new system will have that site updated before too long.

5. > Where is any of this documented?

   As far as I know, it isn't really. There might be a bit of sparse documentation in the PackageEvaluator repository.

**Comment by fingolfin** [comment]
Thank you for the explanations!

**Comment by ararslan** [comment]
No problem. I'm going to close this issue since there isn't really anything actionable to be done here.
