### ISSUE TITLE
multiple Coveralls reports on PRs here

### ISSUE THREAD

**Issue by fingolfin** [JuliaCI/Coverage.jl#300]
For some time now, projects using Coverage.jl plus Coveralls may get multiple Coveralls comments on PRs; see e.g. https://github.com/JuliaCI/CoverageTools.jl/pull/43 or https://github.com/JuliaCI/Coverage.jl/pull/289

<s>I believe this is indeed due to PR #289 and its removal of the `COVERALLS_PARALLEL=true` etc. which we ought to be using per https://github.com/marketplace/actions/coveralls-github-action and https://docs.coveralls.io/parallel-build-webhook (see also the [discussion here](https://github.com/JuliaCI/Coverage.jl/pull/289#discussion_r524818120)). It was removed there to fix other issues, as it is better to get multiple coverage reports than to get none. But now that things are at least working, it would be a good idea to look into this again and see if we can fix the multiple reports somehow.</s>.

It is unclear why exactly this happens.

**Comment by vtjnash** [comment]
The commenting feature used to be completely disabled. Unrelated to that PR, I turned them on. That doesn't affect other projects.

**Comment by DilumAluthge** [comment]
On this repo (JuliaCI/Coverage.jl), the problem seems to be solved now. PRs made to this repo only have a single Coveralls comment and a single Codecov comment.

So I'm going to close this issue. If you have an example repo where this problem is still happening, let me know and we can reopen this issue.
