### ISSUE TITLE
Excluding some files from coverage

### ISSUE THREAD

**Issue by jzuhone** [JuliaCI/Coverage.jl#44]
Hello,

Is there a way to exclude a file from coverage?

It's a file that generates a bunch of symbols using a macro, and I've tried several ways to make it fall under test coverage but none of them have worked, unfortunately.

**Comment by pluskid** [comment]
+1 for this feature. In Mocha.jl, some of the components using GPU cannot be tested on Travis-CI due to absence of GPU devices. I'm currently using a hack to ignore a subdirectory. But I think it might be useful to have a more principled way of ignoring some files. For example

1. Using something similar to `.gitignore` to specify patterns of files to be ignored.
2. Automatically ignore files that have not been loaded. In Mocha.jl, the whole codebase for GPU backend is not loaded if GPU is not enabled in the environment variable. It might be good if coverage could report only the files that are actually loaded during the test. Though I'm not sure whether this is a generally applicable situation for other packages.

**Comment by vtjnash** [comment]
Moved to https://github.com/JuliaCI/CoverageTools.jl/issues/33

**Comment by kongdd** [comment]
Is this feature implemented now?

**Comment by DilumAluthge** [comment]
No, it's just being tracked in https://github.com/JuliaCI/CoverageTools.jl/issues/33 (instead of on this repo$.
