### ISSUE TITLE
Document calling from command line

### ISSUE THREAD

**Issue by jgoldfar** [JuliaCI/Coverage.jl#98]
I would submit a PR if I knew exactly what the intended use was, but this https://github.com/IainNZ/Coverage.jl/blob/master/src/memalloc.jl#L58 caught me when I was trying to write a coverage command line script.

**Comment by IainNZ** [comment]
ping @timholy, who wrote that

**Comment by timholy** [comment]
That line contains everything I remember about this (and more). Looks like it has to be run from `Coverage/src`, and you'd presumably have to update the `find` path to 0.4.

Do you have specific questions?

**Comment by spk83** [comment]
@timholy I ran into issue because of the line pointed by @jgoldfar . I am using Coverage.jl in a command line script and I was passing arg to the script which was being read by the https://github.com/JuliaCI/Coverage.jl/blob/master/src/memalloc.jl#L60 as a file, very surprising. I don't understand why it has to read args from command line. Because of this you cant use Coverage.jl in a script which you want to run with some args in non-interactive mode

**Comment by omus** [comment]
I think we should delete the [non-interactive logic in Coverage.jl](https://github.com/JuliaCI/Coverage.jl/blob/08f64bcc43ccac1b10382383db40942997c6669f/src/memalloc.jl#L58-L62) as it is an issue for scripts which import Coverage and it's rather trivial to do with:

```
julia -e "using Coverage; println(Coverage.analyze_malloc_files(ARGS))"
```

**Comment by jgoldfar** [comment]
It would probably be prudent to find a way to estimate how much that would break, seeing as it was added for a reason at some point.
